name: "🛠 Build Workflow"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: 🛠 Build
        run: |
          xcodebuild -configuration Debug
