name: 🧪 Test Workflow
on: push

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer

jobs:
  test:
    name: 🛠 Build and 🧪 Test
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: 🛠 Build
        run: |
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro' \
            build-for-testing
      - name: 🧪 Test
        run: |
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro' \
            test-without-building
